### ISSUE TITLE
Saved payment validation returns error

### ISSUE THREAD

**Issue by theritesite** [woocommerce/woocommerce-gutenberg-products-block#3618]
## Describe the bug
When using saved payments on the checkout block, the checkout process errors out visibly to front end users. The error is:
payment_data[1][value] is not of type string,boolean.

## To reproduce
1. In my account, add a payment method, mark it as default or the only one.
2. Add any product type to the cart
3. Checkout regularly using the saved card as payment type, don't change the saved card.
4. Hit complete checkout
5. See error above checkout

## Expected behavior
Checkout works.

## Screenshots

![blocks-validation-error](https://user-images.githubusercontent.com/26701248/103379388-aea2e300-4aa2-11eb-9f53-0745771f58a2.jpg)

### WordPress (please complete the following information):
* Core version: 5.5.3
* WooCommerce version: 4.7.0
* WooCommerce Blocks version: 4.1.0
* Site language: English
* Any other plugins installed: WooCommerce Stripe Gateway 4.5.5

## Additional context
Seems to have been introduced with validation in 4.1.0

**Comment by senadir** [comment]
I'm not able to reproduce this issue, but I'm still going to investigate it.

What I did:
- I have several testing cards saved to my account.
- I added a regular product to my cart and tried to checkout.
- I left the first credit card that was selected and placed order: ✅ It worked.
- I selected a different credit card and placed order: ✅ It worked.

**Comment by senadir** [comment]
Also, do you happen to have a live website where I can test this and see the network payload.

**Comment by theritesite** [comment]
Yeah! https://test-cranksports.pantheonsite.io/

**Comment by senadir** [comment]
I managed to reproduce the issue on your website, I'm not fully sure why it's happening for you.

**What happens:**
- `payment_data` contains the selected payment method, between those are `wc-stripe-payment-token`.
- In our code, we ensure that value is a string, and we validate it in the server as a string.
- In your website, that value is an integer and not a string
![image](https://user-images.githubusercontent.com/6165348/103381342-ca7ea700-4aeb-11eb-98e7-a00db52c0b64.png)
- In theory, this issue was fixed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2450

> normalize tokenId to string everywhere. This was a tricky one, but needed because it made the conditional in the use-payment-processing hook in Stripe payment method more reliable. Also accounts for the fact that payment methods likely will have strings as source ids/tokens, not numbers.

I can't reproduce this issue locally yet, and because I can't reproduce it, I can't fix it.

If this is a blocking issue that is preventing you from using your website, you can update this file and this line

https://github.com/woocommerce/woocommerce-gutenberg-products-block//blob/df7da548af75f31030e5f41eb2690965b6045556/src/StoreApi/Routes/Checkout.php#L92

To this value `'type' => [ 'string', 'integer', 'boolean' ],`. This is an intermittent solution that would be lost by the next update.

**Comment by senadir** [comment]
I'd also suggest you update WooCommerce and WooCommerce Stripe Gateway to the latest versions.

**Comment by senadir** [comment]
So I managed to scope down the issue, payment methods added from my-account suffer from this issue, payment methods saved directly from checkout doesn't have this issue.

I'm going to update the testing steps for this issue.

**Comment by theritesite** [comment]
Awesome! Thank you for the quick response and debugging!
As a side note, I have a staging server with updated versions and the error persists
